# Jira Configuration
jira:
  # Your Jira email address
  username: your.email@company.com
  # Your Jira API token (generate from Atlassian account settings)
  apiToken: your_jira_api_token
  # Your Jira instance URL
  baseUrl: https://your-company.atlassian.net

# Harvest Configuration
harvest:
  # Your Harvest personal access token (get from https://id.getharvest.com/developers)
  accessToken: your_personal_access_token
  accountId: # Will be set automatically
  projectId: # Optional, can be selected during first run
  taskId: # Optional, can be selected during first run

# NOTE: Configuration template

# WARN: Make sure to update these values
